name: Deploy site

on:
  push:
    branches: [main]
    paths:
      - site/**
      - .github/workflows/pages.yml
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    name: Публикация
    runs-on: ubuntu-latest
    steps:
      - name: Исходники
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Сборка ветки gh-pages
        run: |
          git config user.name  'github-pages'
          git config user.email 'github-pages@users.noreply.github.com'
          git checkout --orphan gh-pages
          git reset
          git add -f site
          git commit -m 'Публикация сайта'
          git push --force origin gh-pages